services:
  - type: web
    name: mulpath
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3001
      - key: SEPOLIA_RPC_URL
        value: https://ethereum-sepolia-rpc.publicnode.com
      - key: PRIVATE_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        value: 0xa5c3D7BB4C52Ed17dCF5De132e01141b3cD0295D
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PLANTNET_API_KEY
        sync: false
