/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FormulationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "formulations"
      | "getFormulationBatches"
      | "registerFormulation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FormulationRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "formulations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFormulationBatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFormulation",
    values: [BigNumberish, string, string[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "formulations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFormulationBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFormulation",
    data: BytesLike
  ): Result;
}

export namespace FormulationRegisteredEvent {
  export type InputTuple = [
    formulationId: BigNumberish,
    name: string,
    qrCodeUrl: string,
    timestamp: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [
    formulationId: bigint,
    name: string,
    qrCodeUrl: string,
    timestamp: bigint,
    registrar: string
  ];
  export interface OutputObject {
    formulationId: bigint;
    name: string;
    qrCodeUrl: string;
    timestamp: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FormulationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FormulationRegistry;
  waitForDeployment(): Promise<this>;

  interface: FormulationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  formulations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string] & {
        formulationId: bigint;
        name: string;
        qrCodeUrl: string;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;

  getFormulationBatches: TypedContractMethod<
    [_formulationId: BigNumberish],
    [string[]],
    "view"
  >;

  registerFormulation: TypedContractMethod<
    [
      _formulationId: BigNumberish,
      _name: string,
      _sourceBatchIds: string[],
      _qrCodeUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "formulations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string] & {
        formulationId: bigint;
        name: string;
        qrCodeUrl: string;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFormulationBatches"
  ): TypedContractMethod<[_formulationId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "registerFormulation"
  ): TypedContractMethod<
    [
      _formulationId: BigNumberish,
      _name: string,
      _sourceBatchIds: string[],
      _qrCodeUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FormulationRegistered"
  ): TypedContractEvent<
    FormulationRegisteredEvent.InputTuple,
    FormulationRegisteredEvent.OutputTuple,
    FormulationRegisteredEvent.OutputObject
  >;

  filters: {
    "FormulationRegistered(uint256,string,string,uint256,address)": TypedContractEvent<
      FormulationRegisteredEvent.InputTuple,
      FormulationRegisteredEvent.OutputTuple,
      FormulationRegisteredEvent.OutputObject
    >;
    FormulationRegistered: TypedContractEvent<
      FormulationRegisteredEvent.InputTuple,
      FormulationRegisteredEvent.OutputTuple,
      FormulationRegisteredEvent.OutputObject
    >;
  };
}
