/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GeoFenceValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "approvedZones"
      | "getApprovedZone"
      | "setApprovedZone"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ZoneUpdated"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approvedZones",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedZone",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedZone",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvedZones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedZone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedZone",
    data: BytesLike
  ): Result;
}

export namespace ZoneUpdatedEvent {
  export type InputTuple = [
    species: string,
    zoneHash: string,
    updater: AddressLike
  ];
  export type OutputTuple = [
    species: string,
    zoneHash: string,
    updater: string
  ];
  export interface OutputObject {
    species: string;
    zoneHash: string;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GeoFenceValidator extends BaseContract {
  connect(runner?: ContractRunner | null): GeoFenceValidator;
  waitForDeployment(): Promise<this>;

  interface: GeoFenceValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  approvedZones: TypedContractMethod<[arg0: string], [string], "view">;

  getApprovedZone: TypedContractMethod<[_species: string], [string], "view">;

  setApprovedZone: TypedContractMethod<
    [_species: string, _zoneHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approvedZones"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getApprovedZone"
  ): TypedContractMethod<[_species: string], [string], "view">;
  getFunction(
    nameOrSignature: "setApprovedZone"
  ): TypedContractMethod<
    [_species: string, _zoneHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ZoneUpdated"
  ): TypedContractEvent<
    ZoneUpdatedEvent.InputTuple,
    ZoneUpdatedEvent.OutputTuple,
    ZoneUpdatedEvent.OutputObject
  >;

  filters: {
    "ZoneUpdated(string,string,address)": TypedContractEvent<
      ZoneUpdatedEvent.InputTuple,
      ZoneUpdatedEvent.OutputTuple,
      ZoneUpdatedEvent.OutputObject
    >;
    ZoneUpdated: TypedContractEvent<
      ZoneUpdatedEvent.InputTuple,
      ZoneUpdatedEvent.OutputTuple,
      ZoneUpdatedEvent.OutputObject
    >;
  };
}
