/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "FormulationRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FormulationRegistry__factory>;
    getContractFactory(
      name: "GeoFenceValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GeoFenceValidator__factory>;
    getContractFactory(
      name: "HarvestRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HarvestRegistry__factory>;
    getContractFactory(
      name: "HerbTraceability",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HerbTraceability__factory>;

    getContractAt(
      name: "FormulationRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FormulationRegistry>;
    getContractAt(
      name: "GeoFenceValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GeoFenceValidator>;
    getContractAt(
      name: "HarvestRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HarvestRegistry>;
    getContractAt(
      name: "HerbTraceability",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HerbTraceability>;

    deployContract(
      name: "FormulationRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FormulationRegistry>;
    deployContract(
      name: "GeoFenceValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GeoFenceValidator>;
    deployContract(
      name: "HarvestRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HarvestRegistry>;
    deployContract(
      name: "HerbTraceability",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HerbTraceability>;

    deployContract(
      name: "FormulationRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FormulationRegistry>;
    deployContract(
      name: "GeoFenceValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GeoFenceValidator>;
    deployContract(
      name: "HarvestRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HarvestRegistry>;
    deployContract(
      name: "HerbTraceability",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HerbTraceability>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
