/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HarvestRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "harvests" | "registerHarvest"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HarvestRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "harvests", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerHarvest",
    values: [string, string, string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "harvests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerHarvest",
    data: BytesLike
  ): Result;
}

export namespace HarvestRegisteredEvent {
  export type InputTuple = [
    batchId: string,
    species: string,
    gpsHash: string,
    zoneValidated: boolean,
    timestamp: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [
    batchId: string,
    species: string,
    gpsHash: string,
    zoneValidated: boolean,
    timestamp: bigint,
    registrar: string
  ];
  export interface OutputObject {
    batchId: string;
    species: string;
    gpsHash: string;
    zoneValidated: boolean;
    timestamp: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HarvestRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HarvestRegistry;
  waitForDeployment(): Promise<this>;

  interface: HarvestRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  harvests: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, string] & {
        batchId: string;
        species: string;
        gpsHash: string;
        zoneValidated: boolean;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;

  registerHarvest: TypedContractMethod<
    [
      _batchId: string,
      _species: string,
      _gpsHash: string,
      _zoneValidated: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "harvests"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, string] & {
        batchId: string;
        species: string;
        gpsHash: string;
        zoneValidated: boolean;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerHarvest"
  ): TypedContractMethod<
    [
      _batchId: string,
      _species: string,
      _gpsHash: string,
      _zoneValidated: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HarvestRegistered"
  ): TypedContractEvent<
    HarvestRegisteredEvent.InputTuple,
    HarvestRegisteredEvent.OutputTuple,
    HarvestRegisteredEvent.OutputObject
  >;

  filters: {
    "HarvestRegistered(string,string,string,bool,uint256,address)": TypedContractEvent<
      HarvestRegisteredEvent.InputTuple,
      HarvestRegisteredEvent.OutputTuple,
      HarvestRegisteredEvent.OutputObject
    >;
    HarvestRegistered: TypedContractEvent<
      HarvestRegisteredEvent.InputTuple,
      HarvestRegisteredEvent.OutputTuple,
      HarvestRegisteredEvent.OutputObject
    >;
  };
}
