/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HerbTraceabilityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "authorizeLab"
      | "authorizedLabs"
      | "batches"
      | "registerBatch"
      | "revokeLab"
      | "transferOwnership"
      | "updateBatchState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "BatchStateChanged"
      | "LabAuthorized"
      | "LabRevoked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeLab",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedLabs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLab",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBatchState",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeLab",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedLabs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeLab", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBatchState",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: string,
    collector: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    collector: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    collector: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchStateChangedEvent {
  export type InputTuple = [
    batchId: string,
    newState: BigNumberish,
    updater: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    newState: bigint,
    updater: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    newState: bigint;
    updater: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LabAuthorizedEvent {
  export type InputTuple = [lab: AddressLike];
  export type OutputTuple = [lab: string];
  export interface OutputObject {
    lab: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LabRevokedEvent {
  export type InputTuple = [lab: AddressLike];
  export type OutputTuple = [lab: string];
  export interface OutputObject {
    lab: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    batchId: string,
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HerbTraceability extends BaseContract {
  connect(runner?: ContractRunner | null): HerbTraceability;
  waitForDeployment(): Promise<this>;

  interface: HerbTraceabilityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  authorizeLab: TypedContractMethod<[_lab: AddressLike], [void], "nonpayable">;

  authorizedLabs: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  batches: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint] & {
        batchId: string;
        currentOwner: string;
        collector: string;
        state: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  registerBatch: TypedContractMethod<[_batchId: string], [void], "nonpayable">;

  revokeLab: TypedContractMethod<[_lab: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [_batchId: string, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBatchState: TypedContractMethod<
    [_batchId: string, _newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeLab"
  ): TypedContractMethod<[_lab: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedLabs"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint] & {
        batchId: string;
        currentOwner: string;
        collector: string;
        state: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<[_batchId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeLab"
  ): TypedContractMethod<[_lab: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [_batchId: string, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBatchState"
  ): TypedContractMethod<
    [_batchId: string, _newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BatchStateChanged"
  ): TypedContractEvent<
    BatchStateChangedEvent.InputTuple,
    BatchStateChangedEvent.OutputTuple,
    BatchStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "LabAuthorized"
  ): TypedContractEvent<
    LabAuthorizedEvent.InputTuple,
    LabAuthorizedEvent.OutputTuple,
    LabAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "LabRevoked"
  ): TypedContractEvent<
    LabRevokedEvent.InputTuple,
    LabRevokedEvent.OutputTuple,
    LabRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(string,address,uint256)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "BatchStateChanged(string,uint8,address,uint256)": TypedContractEvent<
      BatchStateChangedEvent.InputTuple,
      BatchStateChangedEvent.OutputTuple,
      BatchStateChangedEvent.OutputObject
    >;
    BatchStateChanged: TypedContractEvent<
      BatchStateChangedEvent.InputTuple,
      BatchStateChangedEvent.OutputTuple,
      BatchStateChangedEvent.OutputObject
    >;

    "LabAuthorized(address)": TypedContractEvent<
      LabAuthorizedEvent.InputTuple,
      LabAuthorizedEvent.OutputTuple,
      LabAuthorizedEvent.OutputObject
    >;
    LabAuthorized: TypedContractEvent<
      LabAuthorizedEvent.InputTuple,
      LabAuthorizedEvent.OutputTuple,
      LabAuthorizedEvent.OutputObject
    >;

    "LabRevoked(address)": TypedContractEvent<
      LabRevokedEvent.InputTuple,
      LabRevokedEvent.OutputTuple,
      LabRevokedEvent.OutputObject
    >;
    LabRevoked: TypedContractEvent<
      LabRevokedEvent.InputTuple,
      LabRevokedEvent.OutputTuple,
      LabRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(string,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
